# Generated by Django 4.2.16 on 2024-09-28 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scrumptious', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
