# Generated by Django 4.2.16 on 2024-09-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
